### ISSUE TITLE
can't be too mad at ya

### ISSUE THREAD

**Issue by nosaturn** [Bobby-McGonigle/Cisco-RoomDevice-Macro-Projects-Examples#1]
for a moment i was kinda like, hey, that's the what i wrote  (https://github.com/nosaturn/CiscoTelePresenceEndpoints), but then you took it a bunch of extra steps and then gave it some strong documentation. Bravo!

**Comment by Bobby-McGonigle** [comment]
Ha Thanks, I assure you, we both came across this solution on our own. I did see your's when you posted the link in the xApi group and that's what prompted me to start pushing my work into git.
